[project]
name = "blogwebapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgiref>=3.11.1",
    "django>=6.0.5",
    "django-axes>=8.3.1",
    "django-debug-toolbar>=6.3.0",
    "django-extensions>=4.1",
    "django-ipware>=7.0.1",
    "gevent>=26.5.0",
    "gunicorn>=26.0.0",
    "markdown>=3.10.2",
    "pillow>=12.2.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "redis[hiredis]>=8.0.0",
    "sqlparse>=0.5.5",
]
