# Generated by Django 6.0.2 on 2026-04-16 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('publish_timestamp', models.DateTimeField(default=datetime.datetime(2026, 4, 16, 16, 34, 30, 491592, tzinfo=datetime.timezone.utc))),
                ('is_published', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
