# Generated by Django 6.0.2 on 2026-04-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 16, 16, 46, 45, 850219, tzinfo=datetime.timezone.utc)),
        ),
    ]
