# Generated by Django 6.0.2 on 2026-04-16 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0002_alter_post_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
