# Generated by Django 6.0.2 on 2026-04-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0003_alter_post_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
