# Generated by Django 6.0.2 on 2026-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Publish'), (False, 'Draft')], default=False, max_length=7),
        ),
    ]
