# Generated by Django 6.0.5 on 2026-05-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0006_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='null', unique=True),
            preserve_default=False,
        ),
    ]
