# Generated by Django 6.0.5 on 2026-07-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0009_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
