# Generated by Django 6.0.5 on 2026-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0010_alter_tag_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='displayed_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='counts',
        ),
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
